---
name: "Semantic Release"

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  auto-release:
    if: ${{ (github.ref_name == 'main' || github.ref_name == 'develop') && github.event.workflow_run.conclusion == 'success' }}
    name: "Auto Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          ref: $GITHUB_REF
          path: './'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Setup package.json
        run: echo '{"name":"demo", "devDependencies":{"@semantic-release/git":"^10.0.1","@semantic-release/exec":"^6.0.3","semantic-release":"^23.0.8", "@semantic-release/changelog":"^6.0.3", "@saithodev/semantic-release-backmerge":"^4.0.1", "@semantic-release/github":"^10.0.3"}}' > package.json

      - name: Install dependencies
        run: npm install
      
      - name: permit
        run: chmod +x version.sh

      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
